# PROJECT 1

### Author: Gordon Moenga

## Project Overview

This project focuses on analyzing an e-commerce order dataset to uncover patterns in customer purchases, products, payments, and order activity. The dataset contains 1,200 orders across 14 variables, including customer information, transaction details, order status, shipping information, and promotional data.

The project focuses on data cleaning and preparation to ensure the dataset is accurate, consistent, and ready for subsequent analysis. This involves assessing data quality, handling missing values based on their business meaning, correcting data types, checking for duplicates and inconsistencies, and validating numerical fields.

### Importing Libraries

In [22]:
import pandas as pd
import numpy as np

### Loading the dataset

In [2]:
dataset = pd.read_csv("Dataset for Data Analytics - Sheet1.csv")

### Detailed Data Cleaning

In [3]:
dataset.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
# get the dataset information
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [5]:
dataset.shape

(1200, 14)

In [6]:
# statistical summary of the dataset
dataset.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [7]:
# identify the number of missing data points in each column
dataset.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [8]:
# identify the datatypes for each column
dataset.dtypes

OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

In [9]:
# check for duplicate records
dataset.duplicated().sum()

np.int64(0)

In [10]:
# check for unique values
dataset.nunique()

OrderID            1200
Date                671
CustomerID         1189
Product               7
Quantity              5
UnitPrice          1193
ShippingAddress     655
PaymentMethod         5
OrderStatus           5
TrackingNumber     1200
ItemsInCart          10
CouponCode            3
ReferralSource        5
TotalPrice         1195
dtype: int64

In [11]:
# check for inconsistencies in each categorical column
sorted(dataset['Product'].unique())

['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']

In [12]:
sorted(dataset['PaymentMethod'].unique())

['Cash', 'Credit Card', 'Debit Card', 'Gift Card', 'Online']

In [13]:
sorted(dataset['OrderStatus'].unique())

['Cancelled', 'Delivered', 'Pending', 'Returned', 'Shipped']

In [14]:
sorted(dataset['ReferralSource'].unique())

['Email', 'Facebook', 'Google', 'Instagram', 'Referral']

In [15]:
# converting date column dtype into datetime
dataset['Date'] = pd.to_datetime(dataset['Date'])

In [16]:
# Replace all missing values in the coupon column with 'No Coupon'
dataset['CouponCode'] = dataset['CouponCode'].fillna('No Coupon')

In [26]:
# check whether total price is consistent with unit priice and quantity
calculated_total = dataset['Quantity'] * dataset['UnitPrice']

(dataset['TotalPrice'] == calculated_total).sum()

np.int64(1066)

In [29]:
dataset['CalculatedTotal'] = dataset['Quantity'] * dataset['UnitPrice']

dataset['PriceDifference'] = (
    dataset['TotalPrice'] - dataset['CalculatedTotal']
)

dataset[dataset['PriceDifference'] != 0][
    ['OrderID', 'Quantity', 'UnitPrice', 'TotalPrice',
     'CalculatedTotal', 'PriceDifference']
].head(10)

,OrderID,Quantity,UnitPrice,TotalPrice,CalculatedTotal,PriceDifference
2,ORD200002,5,550.68,2753.40,2753.40,4.547474e-13
10,ORD200010,5,625.97,3129.85,3129.85,-4.547474e-13
11,ORD200011,3,49.14,147.42,147.42,-2.842171e-14
32,ORD200032,5,536.72,2683.60,2683.60,-4.547474e-13
39,ORD200039,3,256.46,769.38,769.38,1.136868e-13
41,ORD200041,3,611.45,1834.35,1834.35,-2.273737e-13
43,ORD200043,3,499.21,1497.63,1497.63,2.273737e-13
55,ORD200055,3,344.40,1033.20,1033.20,2.273737e-13
56,ORD200056,3,479.21,1437.63,1437.63,2.273737e-13
64,ORD200064,3,130.61,391.83,391.83,-5.684342e-14

In [27]:
calculated_total = dataset['Quantity'] * dataset['UnitPrice']

matches = np.isclose(
    dataset['TotalPrice'],
    calculated_total
)

matches.sum()

np.int64(1200)

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [25]:
findings = pd.DataFrame({
    'Key Finding': [
        'Missing values in CouponCode',
        'Date stored as object',
        'No duplicate records',
        'Categorical values were consistent',
        'CustomerID had no missing values',
        'Numerical values were within reasonable ranges',
        'TotalPrice initially appeared inconsistent with Quantity × UnitPrice'
    ],
    'What We Did': [
        'Replaced missing values with "No Coupon"',
        'Converted Date to datetime',
        'Checked for duplicate rows',
        'Reviewed categorical columns',
        'Verified CustomerID completeness',
        'Reviewed descriptive statistics',
        'Validated the calculation using np.isclose() rather than exact equality'
    ],
    'Why': [
        'Missing values represented orders where no coupon was used',
        'Enables reliable date-based analysis',
        'Duplicates could distort analysis',
        'Prevents inconsistent category grouping',
        'Customer IDs are required for customer-level analysis',
        'Identifies potentially invalid values',
        'Floating-point precision can create extremely small differences when comparing decimal values'
    ],
    'Impact': [
        'Preserved all 1,200 orders and made coupon status explicit',
        'Dataset is ready for temporal analysis',
        'No records needed to be removed',
        'No category standardization was required',
        'Customer information was fully preserved',
        'No numerical corrections were required',
        'Confirmed that TotalPrice is mathematically consistent with Quantity × UnitPrice; no records required correction'
    ]
})

findings

,Key Finding,What We Did,Why,Impact
0,Missing values in CouponCode,"Replaced missing values with ""No Coupon""",Missing values represented orders where no cou...,"Preserved all 1,200 orders and made coupon sta..."
1,Date stored as object,Converted Date to datetime,Enables reliable date-based analysis,Dataset is ready for temporal analysis
2,No duplicate records,Checked for duplicate rows,Duplicates could distort analysis,No records needed to be removed
3,Categorical values were consistent,Reviewed categorical columns,Prevents inconsistent category grouping,No category standardization was required
4,CustomerID had no missing values,Verified CustomerID completeness,Customer IDs are required for customer-level a...,Customer information was fully preserved
5,Numerical values were within reasonable ranges,Reviewed descriptive statistics,Identifies potentially invalid values,No numerical corrections were required
6,TotalPrice initially appeared inconsistent wit...,Validated the calculation using np.isclose() r...,Floating-point precision can create extremely ...,Confirmed that TotalPrice is mathematically co...

In [31]:
dataset.to_csv('cleaned_dataset.csv', index=False)